Security definition generation from AuthenticationProviderKey
Burgyn/MMLib.SwaggerForOcelot pull request #205
Opened 2021-11-07 13:11 UTC by bodnarkevin

As suggested in #204 , a simple implemenation of security definition generation from AuthenticationProviderKey

2021-11-08 07:45 UTC, Burgyn commented
I am after appendix surgery.  I'll look into it when I get back from the hospital.

2021-11-08 07:51 UTC, bodnarkevin commented
That's fine, get well soon.

2021-11-20 08:18 UTC, Burgyn requested changes
Hi,
thank you for this PR.

please follow codefactor bot recommendations. (missing xml comment). After their fixing, I will approve this PR

2021-11-20 08:18 UTC, Burgyn commented on src/MMLib.SwaggerForOcelot/Transformation/SwaggerJsonTransformer.cs
> +                return;
```suggestion
           {
                return;
           }
```

2021-11-20 14:13 UTC, bodnarkevin commented on src/MMLib.SwaggerForOcelot/Transformation/SwaggerJsonTransformer.cs
> +                return;
Done

2021-11-20 14:14 UTC, bodnarkevin commented
Added comments. Thank You

2021-11-20 14:23 UTC, merged