implemented a workaround for Conul service discovary support.
Burgyn/MMLib.SwaggerForOcelot pull request #288
Opened 2024-03-11 18:53 UTC by raga70

implemented a workaround for Conul service discovery. Although the solution in this PR works  (please take it as  just guidance on how to fix it) , I did have time to get fully familiar with your code base and just aplied a hot fix.

PS:   my ide made a bit of a  reformatting on the files I touched (sorry for the extra hassle when reviewing ), if you have any questions send me a message

2024-03-14 19:26 UTC, Burgyn commented
Hi @raga70,

thanks for your PR. I can merge this PR if you:
- fix codefactor bot issues
- my comment
- and revert formatting of touched methods

thanks.

2024-03-14 19:27 UTC, Burgyn requested changes

2024-03-14 19:27 UTC, Burgyn commented on src/MMLib.SwaggerForOcelot/Repositories/DownstreamSwaggerDocsRepository.cs
> +            if (!(url.StartsWith("http://") || url.StartsWith("https://"))) //the url that gets constructed when using consul misses the http schema , and trows an exception
Use `StringComparison.InvariantCultureIgnoreCase`. and remove comments

2024-03-15 11:47 UTC, raga70 commented
Hi @Burgyn  I committed the changes you requested .

2024-03-18 17:57 UTC, Burgyn approved these changes

2024-03-18 18:02 UTC, Burgyn commented
Hi @raga70,

unfortunately your changes failed tests.

Please fix tests.

2024-03-26 20:37 UTC, raga70 commented
I added nullability to my ServiceProviderType since the ServiceProviderConfiguration is in fact  null when unit testing

2024-03-27 09:35 UTC, Burgyn approved these changes

2024-03-27 09:35 UTC, merged